version: '3'

services:
  redis01:
    build: redis-config
    ports:
      - '6380:6379'
    networks:
      - host
    env_file:
      - 'redis-config/env/master_variables.env'

  redis02:
    build: redis-config
    ports:
      - '6381:6379'
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - 'redis-config/env/slave_variables.env'

  redis03:
    build: redis-config
    ports:
      - '6382:6379'
    depends_on:
      - redis01
    networks:
      - host
    env_file:
      - 'redis-config/env/slave_variables.env'

  proxy:
    build: ./haproxy
    depends_on:
      - redis01
      - redis02
      - redis03
    networks:
      - host
    ports:
      - '9911:8080'
      - '8080:80'

networks:
  host: